"""
University database seeding script
Populates the universities table with realistic data including scholarships
"""
import os
from supabase import create_client, Client
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Initialize Supabase client directly
SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_KEY = os.getenv("SUPABASE_KEY")

if not SUPABASE_URL or not SUPABASE_KEY:
    raise ValueError("SUPABASE_URL and SUPABASE_KEY must be set in .env file")

supabase: Client = create_client(SUPABASE_URL, SUPABASE_KEY)

# Realistic university data with scholarships
UNIVERSITIES = [
    # USA - Top Universities
    {
        "name": "Massachusetts Institute of Technology (MIT)",
        "country": "USA",
        "city": "Cambridge, MA",
        "ranking": 1,
        "programs_offered": ["Computer Science", "Engineering", "Data Science", "AI/ML", "Business Analytics", "Mathematics", "Physics"],
        "min_gpa": 3.8,
        "min_ielts": 7.5,
        "min_toefl": 110,
        "requires_gre": True,
        "requires_gmat": False,
        "tuition_min": 53000,
        "tuition_max": 55000,
        "living_cost_yearly": 20000,
        "has_scholarships": True,
        "scholarship_types": ["Merit-based", "Need-based", "Research Assistantship"],
        "scholarship_amount_min": 10000,
        "scholarship_amount_max": 75000,
        "scholarship_deadline": "December 15",
        "acceptance_rate": 3.9,
        "description": "Leading technology research university known for innovation and cutting-edge research in STEM fields."
    },
    {
        "name": "Stanford University",
        "country": "USA",
        "city": "Stanford, CA",
        "ranking": 2,
        "programs_offered": ["Computer Science", "Engineering", "Business", "Data Science", "AI/ML", "Design", "Medicine"],
        "min_gpa": 3.7,
        "min_ielts": 7.0,
        "min_toefl": 105,
        "requires_gre": True,
        "requires_gmat": False,
        "tuition_min": 52000,
        "tuition_max": 55000,
        "living_cost_yearly": 22000,
        "has_scholarships": True,
        "scholarship_types": ["Merit-based", "Need-based", "Knight-Hennessy Scholars"],
        "scholarship_amount_min": 15000,
        "scholarship_amount_max": 77000,
        "scholarship_deadline": "December 1",
        "acceptance_rate": 3.7,
        "description": "Premier private research university in Silicon Valley, fostering entrepreneurship and innovation."
    },
    {
        "name": "Harvard University",
        "country": "USA",
        "city": "Cambridge, MA",
        "ranking": 3,
        "programs_offered": ["Business", "Law", "Engineering", "Medicine", "Data Science", "Public Policy", "Economics"],
        "min_gpa": 3.8,
        "min_ielts": 7.5,
        "min_toefl": 110,
        "requires_gre": True,
        "requires_gmat": True,
        "tuition_min": 51000,
        "tuition_max": 54000,
        "living_cost_yearly": 21000,
        "has_scholarships": True,
        "scholarship_types": ["Need-based", "Merit-based", "Fellowship"],
        "scholarship_amount_min": 12000,
        "scholarship_amount_max": 75000,
        "scholarship_deadline": "December 15",
        "acceptance_rate": 3.4,
        "description": "Oldest and one of the most prestigious universities in the United States with a global reputation."
    },
    {
        "name": "University of California, Berkeley",
        "country": "USA",
        "city": "Berkeley, CA",
        "ranking": 10,
        "programs_offered": ["Computer Science", "Engineering", "Data Science", "Business", "Environmental Science", "Public Health"],
        "min_gpa": 3.5,
        "min_ielts": 6.5,
        "min_toefl": 90,
        "requires_gre": True,
        "requires_gmat": False,
        "tuition_min": 28000,
        "tuition_max": 30000,
        "living_cost_yearly": 18000,
        "has_scholarships": True,
        "scholarship_types": ["Merit-based", "Teaching Assistantship", "Research Assistantship"],
        "scholarship_amount_min": 8000,
        "scholarship_amount_max": 48000,
        "scholarship_deadline": "January 15",
        "acceptance_rate": 14.3,
        "description": "Top public research university known for academic excellence and social activism."
    },
    {
        "name": "Carnegie Mellon University",
        "country": "USA",
        "city": "Pittsburgh, PA",
        "ranking": 15,
        "programs_offered": ["Computer Science", "AI/ML", "Robotics", "Engineering", "Data Science", "Information Systems"],
        "min_gpa": 3.6,
        "min_ielts": 7.0,
        "min_toefl": 100,
        "requires_gre": True,
        "requires_gmat": False,
        "tuition_min": 48000,
        "tuition_max": 52000,
        "living_cost_yearly": 17000,
        "has_scholarships": True,
        "scholarship_types": ["Merit-based", "Research Assistantship", "Industry Sponsored"],
        "scholarship_amount_min": 10000,
        "scholarship_amount_max": 52000,
        "scholarship_deadline": "January 5",
        "acceptance_rate": 15.4,
        "description": "World leader in computer science, AI, and robotics education and research."
    },
    {
        "name": "University of Michigan - Ann Arbor",
        "country": "USA",
        "city": "Ann Arbor, MI",
        "ranking": 18,
        "programs_offered": ["Engineering", "Business", "Computer Science", "Data Science", "Public Health", "Law"],
        "min_gpa": 3.4,
        "min_ielts": 6.5,
        "min_toefl": 90,
        "requires_gre": True,
        "requires_gmat": False,
        "tuition_min": 25000,
        "tuition_max": 28000,
        "living_cost_yearly": 16000,
        "has_scholarships": True,
        "scholarship_types": ["Merit-based", "Need-based", "Graduate Assistantship"],
        "scholarship_amount_min": 7000,
        "scholarship_amount_max": 44000,
        "scholarship_deadline": "January 31",
        "acceptance_rate": 20.2,
        "description": "Leading public research university with strong programs across all disciplines."
    },
    {
        "name": "New York University (NYU)",
        "country": "USA",
        "city": "New York, NY",
        "ranking": 25,
        "programs_offered": ["Business", "Finance", "Data Science", "Computer Science", "Arts", "Law", "Medicine"],
        "min_gpa": 3.3,
        "min_ielts": 7.0,
        "min_toefl": 95,
        "requires_gre": True,
        "requires_gmat": True,
        "tuition_min": 45000,
        "tuition_max": 50000,
        "living_cost_yearly": 25000,
        "has_scholarships": True,
        "scholarship_types": ["Merit-based", "International Student Scholarship"],
        "scholarship_amount_min": 8000,
        "scholarship_amount_max": 40000,
        "scholarship_deadline": "January 15",
        "acceptance_rate": 12.8,
        "description": "Major private university in the heart of New York City with global campuses."
    },
    {
        "name": "University of Southern California (USC)",
        "country": "USA",
        "city": "Los Angeles, CA",
        "ranking": 27,
        "programs_offered": ["Computer Science", "Engineering", "Business", "Film", "Data Science", "Gaming"],
        "min_gpa": 3.3,
        "min_ielts": 6.5,
        "min_toefl": 90,
        "requires_gre": True,
        "requires_gmat": False,
        "tuition_min": 43000,
        "tuition_max": 47000,
        "living_cost_yearly": 20000,
        "has_scholarships": True,
        "scholarship_types": ["Merit-based", "Trustee Scholarship", "Presidential Scholarship"],
        "scholarship_amount_min": 10000,
        "scholarship_amount_max": 47000,
        "scholarship_deadline": "December 1",
        "acceptance_rate": 11.4,
        "description": "Leading private research university with strong industry connections in Southern California."
    },
    
    # UK - Top Universities
    {
        "name": "University of Oxford",
        "country": "UK",
        "city": "Oxford",
        "ranking": 4,
        "programs_offered": ["Engineering", "Computer Science", "Business", "Law", "Medicine", "Mathematics", "Philosophy"],
        "min_gpa": 3.7,
        "min_ielts": 7.5,
        "min_toefl": 110,
        "requires_gre": False,
        "requires_gmat": False,
        "tuition_min": 28000,
        "tuition_max": 35000,
        "living_cost_yearly": 15000,
        "has_scholarships": True,
        "scholarship_types": ["Rhodes Scholarship", "Clarendon Fund", "Merit-based"],
        "scholarship_amount_min": 15000,
        "scholarship_amount_max": 50000,
        "scholarship_deadline": "January 20",
        "acceptance_rate": 17.5,
        "description": "Oldest university in the English-speaking world, renowned for academic excellence and research."
    },
    {
        "name": "University of Cambridge",
        "country": "UK",
        "city": "Cambridge",
        "ranking": 5,
        "programs_offered": ["Engineering", "Computer Science", "Mathematics", "Physics", "Medicine", "Economics"],
        "min_gpa": 3.7,
        "min_ielts": 7.5,
        "min_toefl": 110,
        "requires_gre": False,
        "requires_gmat": False,
        "tuition_min": 27000,
        "tuition_max": 34000,
        "living_cost_yearly": 14000,
        "has_scholarships": True,
        "scholarship_types": ["Gates Cambridge", "Cambridge Trust", "College Scholarships"],
        "scholarship_amount_min": 12000,
        "scholarship_amount_max": 48000,
        "scholarship_deadline": "December 2",
        "acceptance_rate": 19.6,
        "description": "One of the world's oldest and most prestigious universities with a strong research focus."
    },
    {
        "name": "Imperial College London",
        "country": "UK",
        "city": "London",
        "ranking": 7,
        "programs_offered": ["Engineering", "Computer Science", "Medicine", "Business", "Data Science", "AI/ML"],
        "min_gpa": 3.5,
        "min_ielts": 7.0,
        "min_toefl": 100,
        "requires_gre": False,
        "requires_gmat": False,
        "tuition_min": 32000,
        "tuition_max": 38000,
        "living_cost_yearly": 16000,
        "has_scholarships": True,
        "scholarship_types": ["President's Scholarship", "ICL Excellence Award"],
        "scholarship_amount_min": 10000,
        "scholarship_amount_max": 38000,
        "scholarship_deadline": "January 10",
        "acceptance_rate": 14.3,
        "description": "Leading science and technology university in London with strong industry partnerships."
    },
    {
        "name": "University College London (UCL)",
        "country": "UK",
        "city": "London",
        "ranking": 9,
        "programs_offered": ["Engineering", "Computer Science", "Architecture", "Medicine", "Economics", "Law"],
        "min_gpa": 3.4,
        "min_ielts": 7.0,
        "min_toefl": 100,
        "requires_gre": False,
        "requires_gmat": False,
        "tuition_min": 26000,
        "tuition_max": 32000,
        "living_cost_yearly": 16000,
        "has_scholarships": True,
        "scholarship_types": ["Global Excellence Scholarship", "Graduate Research Scholarship"],
        "scholarship_amount_min": 8000,
        "scholarship_amount_max": 32000,
        "scholarship_deadline": "January 31",
        "acceptance_rate": 48.0,
        "description": "London's leading multidisciplinary university with a global reputation for research."
    },
    {
        "name": "University of Edinburgh",
        "country": "UK",
        "city": "Edinburgh",
        "ranking": 16,
        "programs_offered": ["Computer Science", "Engineering", "Data Science", "AI/ML", "Medicine", "Business"],
        "min_gpa": 3.3,
        "min_ielts": 6.5,
        "min_toefl": 92,
        "requires_gre": False,
        "requires_gmat": False,
        "tuition_min": 24000,
        "tuition_max": 30000,
        "living_cost_yearly": 12000,
        "has_scholarships": True,
        "scholarship_types": ["Edinburgh Global Scholarship", "School-specific Awards"],
        "scholarship_amount_min": 5000,
        "scholarship_amount_max": 25000,
        "scholarship_deadline": "February 1",
        "acceptance_rate": 40.0,
        "description": "Historic Scottish university with strong research programs and international student community."
    },
    {
        "name": "King's College London",
        "country": "UK",
        "city": "London",
        "ranking": 33,
        "programs_offered": ["Law", "Medicine", "Data Science", "Business", "Computer Science", "Public Policy"],
        "min_gpa": 3.2,
        "min_ielts": 6.5,
        "min_toefl": 90,
        "requires_gre": False,
        "requires_gmat": False,
        "tuition_min": 22000,
        "tuition_max": 28000,
        "living_cost_yearly": 16000,
        "has_scholarships": True,
        "scholarship_types": ["International Scholarship", "Faculty Scholarship"],
        "scholarship_amount_min": 6000,
        "scholarship_amount_max": 28000,
        "scholarship_deadline": "March 1",
        "acceptance_rate": 13.0,
        "description": "One of England's oldest universities with a strong reputation in law and medicine."
    },
    
    # Canada - Top Universities
    {
        "name": "University of Toronto",
        "country": "Canada",
        "city": "Toronto",
        "ranking": 21,
        "programs_offered": ["Computer Science", "Engineering", "Business", "Data Science", "Medicine", "AI/ML"],
        "min_gpa": 3.5,
        "min_ielts": 7.0,
        "min_toefl": 100,
        "requires_gre": True,
        "requires_gmat": False,
        "tuition_min": 30000,
        "tuition_max": 45000,
        "living_cost_yearly": 15000,
        "has_scholarships": True,
        "scholarship_types": ["Lester B. Pearson Scholarship", "Graduate Excellence Award"],
        "scholarship_amount_min": 10000,
        "scholarship_amount_max": 65000,
        "scholarship_deadline": "January 15",
        "acceptance_rate": 43.0,
        "description": "Canada's leading university with world-class research facilities and diverse programs."
    },
    {
        "name": "University of British Columbia (UBC)",
        "country": "Canada",
        "city": "Vancouver",
        "ranking": 34,
        "programs_offered": ["Computer Science", "Engineering", "Business", "Data Science", "Environmental Science"],
        "min_gpa": 3.3,
        "min_ielts": 6.5,
        "min_toefl": 90,
        "requires_gre": True,
        "requires_gmat": False,
        "tuition_min": 28000,
        "tuition_max": 40000,
        "living_cost_yearly": 15000,
        "has_scholarships": True,
        "scholarship_types": ["International Leader of Tomorrow Award", "Graduate Support Initiative"],
        "scholarship_amount_min": 8000,
        "scholarship_amount_max": 55000,
        "scholarship_deadline": "December 1",
        "acceptance_rate": 52.0,
        "description": "Beautiful campus in Vancouver with strong research programs and international focus."
    },
    {
        "name": "McGill University",
        "country": "Canada",
        "city": "Montreal",
        "ranking": 30,
        "programs_offered": ["Engineering", "Medicine", "Business", "Computer Science", "Law", "Life Sciences"],
        "min_gpa": 3.3,
        "min_ielts": 6.5,
        "min_toefl": 90,
        "requires_gre": False,
        "requires_gmat": False,
        "tuition_min": 20000,
        "tuition_max": 35000,
        "living_cost_yearly": 12000,
        "has_scholarships": True,
        "scholarship_types": ["McGill Entrance Scholarship", "Graduate Excellence Fellowship"],
        "scholarship_amount_min": 7000,
        "scholarship_amount_max": 35000,
        "scholarship_deadline": "January 15",
        "acceptance_rate": 46.3,
        "description": "Top Canadian university with a strong international reputation and bilingual environment."
    },
    {
        "name": "University of Waterloo",
        "country": "Canada",
        "city": "Waterloo",
        "ranking": 149,
        "programs_offered": ["Computer Science", "Engineering", "Mathematics", "Data Science", "AI/ML", "Mechatronics"],
        "min_gpa": 3.2,
        "min_ielts": 6.5,
        "min_toefl": 90,
        "requires_gre": False,
        "requires_gmat": False,
        "tuition_min": 25000,
        "tuition_max": 35000,
        "living_cost_yearly": 12000,
        "has_scholarships": True,
        "scholarship_types": ["President's Graduate Scholarship", "Co-op Innovation Award"],
        "scholarship_amount_min": 5000,
        "scholarship_amount_max": 30000,
        "scholarship_deadline": "February 1",
        "acceptance_rate": 53.0,
        "description": "Known for co-op programs and strong connections with tech industry, especially in computer science."
    },
    
    # Australia - Top Universities
    {
        "name": "University of Melbourne",
        "country": "Australia",
        "city": "Melbourne",
        "ranking": 14,
        "programs_offered": ["Engineering", "Computer Science", "Business", "Medicine", "Law", "Data Science"],
        "min_gpa": 3.5,
        "min_ielts": 6.5,
        "min_toefl": 94,
        "requires_gre": False,
        "requires_gmat": False,
        "tuition_min": 35000,
        "tuition_max": 45000,
        "living_cost_yearly": 18000,
        "has_scholarships": True,
        "scholarship_types": ["Melbourne Graduate Scholarship", "International Research Scholarship"],
        "scholarship_amount_min": 10000,
        "scholarship_amount_max": 45000,
        "scholarship_deadline": "October 31",
        "acceptance_rate": 70.0,
        "description": "Australia's leading university with comprehensive programs and strong research output."
    },
    {
        "name": "Australian National University (ANU)",
        "country": "Australia",
        "city": "Canberra",
        "ranking": 30,
        "programs_offered": ["Computer Science", "Engineering", "Economics", "Public Policy", "Data Science"],
        "min_gpa": 3.3,
        "min_ielts": 6.5,
        "min_toefl": 90,
        "requires_gre": False,
        "requires_gmat": False,
        "tuition_min": 32000,
        "tuition_max": 42000,
        "living_cost_yearly": 16000,
        "has_scholarships": True,
        "scholarship_types": ["ANU Chancellor's International Scholarship", "Research Training Program"],
        "scholarship_amount_min": 15000,
        "scholarship_amount_max": 42000,
        "scholarship_deadline": "November 15",
        "acceptance_rate": 35.0,
        "description": "National research university with strong government and policy connections."
    },
    {
        "name": "University of Sydney",
        "country": "Australia",
        "city": "Sydney",
        "ranking": 19,
        "programs_offered": ["Engineering", "Business", "Computer Science", "Medicine", "Architecture", "Law"],
        "min_gpa": 3.3,
        "min_ielts": 6.5,
        "min_toefl": 90,
        "requires_gre": False,
        "requires_gmat": False,
        "tuition_min": 35000,
        "tuition_max": 45000,
        "living_cost_yearly": 18000,
        "has_scholarships": True,
        "scholarship_types": ["Sydney Scholars Award", "Vice-Chancellor's International Scholarship"],
        "scholarship_amount_min": 8000,
        "scholarship_amount_max": 40000,
        "scholarship_deadline": "November 30",
        "acceptance_rate": 30.0,
        "description": "Historic university in Sydney with beautiful campus and strong academic programs."
    },
    {
        "name": "University of Queensland",
        "country": "Australia",
        "city": "Brisbane",
        "ranking": 43,
        "programs_offered": ["Engineering", "Business", "Data Science", "Medicine", "Environmental Science"],
        "min_gpa": 3.2,
        "min_ielts": 6.5,
        "min_toefl": 87,
        "requires_gre": False,
        "requires_gmat": False,
        "tuition_min": 30000,
        "tuition_max": 40000,
        "living_cost_yearly": 15000,
        "has_scholarships": True,
        "scholarship_types": ["UQ Excellence Scholarship", "International Scholarship"],
        "scholarship_amount_min": 6000,
        "scholarship_amount_max": 38000,
        "scholarship_deadline": "November 30",
        "acceptance_rate": 54.0,
        "description": "Leading Queensland university with strong research focus and international partnerships."
    },
    
    # Germany - Top Universities
    {
        "name": "Technical University of Munich (TUM)",
        "country": "Germany",
        "city": "Munich",
        "ranking": 49,
        "programs_offered": ["Computer Science", "Engineering", "Data Science", "AI/ML", "Robotics", "Physics"],
        "min_gpa": 3.0,
        "min_ielts": 6.5,
        "min_toefl": 88,
        "requires_gre": False,
        "requires_gmat": False,
        "tuition_min": 0,
        "tuition_max": 500,
        "living_cost_yearly": 12000,
        "has_scholarships": True,
        "scholarship_types": ["DAAD Scholarship", "TUM Scholarship"],
        "scholarship_amount_min": 5000,
        "scholarship_amount_max": 15000,
        "scholarship_deadline": "November 30",
        "acceptance_rate": 8.0,
        "description": "Top German technical university with tuition-free education and excellent research facilities."
    },
    {
        "name": "Ludwig Maximilian University of Munich (LMU)",
        "country": "Germany",
        "city": "Munich",
        "ranking": 59,
        "programs_offered": ["Computer Science", "Business", "Law", "Medicine", "Economics", "Physics"],
        "min_gpa": 3.0,
        "min_ielts": 6.5,
        "min_toefl": 80,
        "requires_gre": False,
        "requires_gmat": False,
        "tuition_min": 0,
        "tuition_max": 300,
        "living_cost_yearly": 12000,
        "has_scholarships": True,
        "scholarship_types": ["DAAD Scholarship", "Bavarian State Scholarship"],
        "scholarship_amount_min": 4000,
        "scholarship_amount_max": 12000,
        "scholarship_deadline": "December 15",
        "acceptance_rate": 12.0,
        "description": "Historic German university offering tuition-free education with excellent academic programs."
    },
    
    # Netherlands - Top Universities
    {
        "name": "Delft University of Technology",
        "country": "Netherlands",
        "city": "Delft",
        "ranking": 47,
        "programs_offered": ["Engineering", "Computer Science", "Data Science", "Architecture", "Aerospace"],
        "min_gpa": 3.2,
        "min_ielts": 6.5,
        "min_toefl": 90,
        "requires_gre": False,
        "requires_gmat": False,
        "tuition_min": 18000,
        "tuition_max": 20000,
        "living_cost_yearly": 12000,
        "has_scholarships": True,
        "scholarship_types": ["Justus & Louise van Effen Excellence Scholarship", "TU Delft Scholarship"],
        "scholarship_amount_min": 5000,
        "scholarship_amount_max": 20000,
        "scholarship_deadline": "December 1",
        "acceptance_rate": 14.0,
        "description": "Leading technical university in the Netherlands with strong engineering programs."
    },
    {
        "name": "University of Amsterdam",
        "country": "Netherlands",
        "city": "Amsterdam",
        "ranking": 53,
        "programs_offered": ["Computer Science", "Business", "Data Science", "Economics", "AI/ML", "Psychology"],
        "min_gpa": 3.0,
        "min_ielts": 6.5,
        "min_toefl": 92,
        "requires_gre": False,
        "requires_gmat": False,
        "tuition_min": 15000,
        "tuition_max": 18000,
        "living_cost_yearly": 13000,
        "has_scholarships": True,
        "scholarship_types": ["Amsterdam Excellence Scholarship", "Holland Scholarship"],
        "scholarship_amount_min": 6000,
        "scholarship_amount_max": 18000,
        "scholarship_deadline": "January 15",
        "acceptance_rate": 31.0,
        "description": "Top Dutch university in the heart of Amsterdam with diverse international programs."
    },
    
    # Singapore
    {
        "name": "National University of Singapore (NUS)",
        "country": "Singapore",
        "city": "Singapore",
        "ranking": 11,
        "programs_offered": ["Computer Science", "Engineering", "Business", "Data Science", "AI/ML", "Medicine"],
        "min_gpa": 3.5,
        "min_ielts": 6.5,
        "min_toefl": 92,
        "requires_gre": True,
        "requires_gmat": False,
        "tuition_min": 25000,
        "tuition_max": 35000,
        "living_cost_yearly": 12000,
        "has_scholarships": True,
        "scholarship_types": ["NUS Graduate Scholarship", "President's Graduate Fellowship"],
        "scholarship_amount_min": 12000,
        "scholarship_amount_max": 35000,
        "scholarship_deadline": "November 15",
        "acceptance_rate": 5.0,
        "description": "Asia's leading university with world-class research and strong industry connections."
    },
    {
        "name": "Nanyang Technological University (NTU)",
        "country": "Singapore",
        "city": "Singapore",
        "ranking": 26,
        "programs_offered": ["Engineering", "Computer Science", "Business", "Data Science", "AI/ML"],
        "min_gpa": 3.3,
        "min_ielts": 6.5,
        "min_toefl": 90,
        "requires_gre": True,
        "requires_gmat": False,
        "tuition_min": 22000,
        "tuition_max": 30000,
        "living_cost_yearly": 12000,
        "has_scholarships": True,
        "scholarship_types": ["NTU Research Scholarship", "ASEAN Scholarship"],
        "scholarship_amount_min": 10000,
        "scholarship_amount_max": 30000,
        "scholarship_deadline": "November 30",
        "acceptance_rate": 25.0,
        "description": "Young and innovative university in Singapore with strong focus on technology and innovation."
    },
    
    # Ireland
    {
        "name": "Trinity College Dublin",
        "country": "Ireland",
        "city": "Dublin",
        "ranking": 98,
        "programs_offered": ["Computer Science", "Engineering", "Business", "Data Science", "Medicine", "Law"],
        "min_gpa": 3.2,
        "min_ielts": 6.5,
        "min_toefl": 90,
        "requires_gre": False,
        "requires_gmat": False,
        "tuition_min": 18000,
        "tuition_max": 25000,
        "living_cost_yearly": 12000,
        "has_scholarships": True,
        "scholarship_types": ["Trinity International Scholarship", "Postgraduate Award"],
        "scholarship_amount_min": 5000,
        "scholarship_amount_max": 25000,
        "scholarship_deadline": "March 1",
        "acceptance_rate": 35.0,
        "description": "Ireland's oldest and most prestigious university with strong European connections."
    },
]


def seed_universities():
    """Seed universities table with data"""
    print("Starting university database seeding...")
    print(f"Using Supabase URL: {SUPABASE_URL}")
    
    try:
        # Insert universities
        inserted_count = 0
        for university in UNIVERSITIES:
            try:
                result = supabase.table("universities").insert(university).execute()
                print(f"✓ Inserted: {university['name']}")
                inserted_count += 1
            except Exception as e:
                print(f"✗ Error inserting {university['name']}: {str(e)}")
        
        print(f"\n✅ Successfully seeded {inserted_count} out of {len(UNIVERSITIES)} universities!")
        print("\nUniversities by country:")
        countries = {}
        for uni in UNIVERSITIES:
            country = uni["country"]
            countries[country] = countries.get(country, 0) + 1
        
        for country, count in sorted(countries.items()):
            print(f"  {country}: {count} universities")
            
    except Exception as e:
        print(f"❌ Error during seeding: {str(e)}")


if __name__ == "__main__":
    seed_universities()
